### ISSUE TITLE
Features imported from Hivelytracker?

### ISSUE THREAD

**Issue by SamuraiCrow** [hitchhikr/protrekkr#1]
If this code is still being maintained, I've wanted to see a Tracker-style editor with the track-level playlist features of [HivelyTracker](https://github.com/pete-gordon/hivelytracker) and the sample compression features of ProTrekkr in one project.  Whether it's a new project or a sequel to an existing one, I don't know.

The editor of HivelyTracker needs work and ProTrekkr is heavy on the CPU requirements.  I think Hively precomputes waveforms at startup time to reduce CPU strain.  ProTrekkr allows grouping of tracks and commands making editing easier.

Would you be willing or able to help with such a project?  I can do documentation work as I have been on my attempt at converting the old Google Code import of ProTrekkr.

**Comment by hitchhikr** [comment]
Ptk isn't maintained at the moment, nothing forbid to to fork it.
