### ISSUE TITLE
Haiku: store config at ~/config/settings/protrekkr/ not ./

### ISSUE THREAD

**Issue by SamuraiCrow** [hitchhikr/protrekkr#10]
Since Haiku HPKG packages are mounted as read-only, the directory Protrekkr runs from is read-only and causes segfaults when running with a ptk.cfg file present in the programs base directory. This may be two separate bugs but it needs attention for the Haiku install.

Tested on Haiku Beta 4 latest update, x86-64 CPU and 32 GiB of RAM on hyperthreaded quad-core i7-3770K

**Comment by SamuraiCrow** [comment]
No longer crashes on startup. Issue #6 seems solved. Still stores the config in the wrong directory.

**Comment by hitchhikr** [comment]
What are you going to do about that ?

**Comment by SamuraiCrow** [comment]
When I find time, I'll fix it and submit a pull request. I just made a note here so there would be a record of it.
