### ISSUE TITLE
crash with NoiseTrekker 1.x tracks

### ISSUE THREAD

**Issue by ciros88** [hitchhikr/protrekkr#13]
currently NoiseTrekker 1.x tracks seem to load but then the program crash when trying to play them. any chance to add the support?

**Comment by hitchhikr** [comment]
Do you have any example file ?

**Comment by ciros88** [comment]
NoiseTrekker 1.x (header 'TWNNSNG1'):
http://modland.com/pub/modules/NoiseTrekker/

opposed to

NoiseTrekker 2 (header 'TWNNSNG2'):
http://modland.com/pub/modules/NoiseTrekker%202/

opposed to ProTrekkr headers 'PROTREK' or 'TWNNSNG' ending with '6', 'G' or 'I'

**Comment by hitchhikr** [comment]
This is fixed but 'TWNNSNG1' modules aren't even Noisetrekker 1 but Noisetrekker beta. There is no real interest in using those.

**Comment by hitchhikr** [comment]
Just download Noisetrekker R7 and try to open one of such module.

**Comment by hitchhikr** [comment]
Try them:

https://hitchhikr.net/NoiseTrekker beta v1.6.rar
https://hitchhikr.net/NoiseTrekker R7.rar
https://hitchhikr.net/NoiseTrekker2 R12.rar

**Comment by Kaens** [comment]
> consistent with audio.1.sg detection which mention "v1.6b"
(A quick note from the guy who wrote that there: I'm no expert on the history of noisetrekker/protrekkr! If someone has a solid table of versions vs signatures, I'll be happy to change that one)

**Comment by hitchhikr** [comment]
The synth engine have been heavily modified in protrekkr anyway so loading them into it won't sound near as the original.
Beside all the public ntk modules have been converted to ptk.

**Comment by ciros88** [comment]
so 1.6b means 1.6 beta clearly
@hitchhikr thanks for the links

**Comment by ciros88** [comment]
btw this seems the final ntk version: https://web.archive.org/web/20041017175640/http://amor.rz.hu-berlin.de/~h0444fje/ntk3.2.zip

**Comment by hitchhikr** [comment]
This one wasn't made by Arguru but by the guy who's working on Renoise, the source code of that version have never been published.
