### ISSUE TITLE
"End of Song" command 0F00 doesn't stop .WAV export

### ISSUE THREAD

**Issue by SamuraiCrow** [hitchhikr/protrekkr#4]
When a 0F00 command is encountered by the player, the song stops and returns control to the program.  When the .wav generator encounters that command, it starts writing infinite whitespace to the file and requires a system reset to stop it.  (Version 2.5.5 tested on x86_64 Linux.)  As a workaround, you can replace the F00 with a D00 and add a block with all the tracks silent, then record all but the last block or shorten the last block instead of using D00 so it ends in the right place.

**Comment by hitchhikr** [comment]
Should be fixed.

**Comment by SamuraiCrow** [comment]
Ok.  Yeah you told me via email but I forgot.
