### ISSUE TITLE
``__NO_MIDI__`` define screws up ptk.cfg parsing on startup.

### ISSUE THREAD

**Issue by SamuraiCrow** [hitchhikr/protrekkr#5]
When the ``__NO_MIDI__`` define is passed into the preprocessor, the parse of ptk.cfg fails with a segfault/coredump.  If there isn't a ptk.cfg file present, the program works with the default entries.  Tested on Haiku 64-bit and Linux 64-bit.

**Comment by hitchhikr** [comment]
Can't reproduce the bug.

**Comment by SamuraiCrow** [comment]
It may just be the Haiku branch I was working on.
